# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99404114e28427a40489cd538a575f92f4bd58fb25db401a289ce2e61aa710454e55ce69fb938ea33b18f5fdacf17ec892d6a7ed62b382e808cccff9da0145d

test:
  secret_key_base: 823ee6846daa5b8a0632d4db5d3d43d54863a89395156513539f009bae692cf26b85d82abaccdd8c7c77e45f2638cd05b4fece7103aba0be9d72b839d626d9a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
